[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.bcmath",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.pdo_mysql",
  "nodejs_20"
]

[phases.build]
cmds = [
  "npm ci",
  "npm run build",
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"